_BASE_: "../base-custom_prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "Custom"
  DATAPATH: ""  #TODO: need to specify here
  NUMBER_CLASSES: 200
  MULTILABEL: False
MODEL:
  TYPE: "sam"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01